### ISSUE TITLE
open cert.pem: no such file or directory

### ISSUE THREAD

**Issue by BenHall** [cloud66/habitus#13]
When I try and run habitus (Linux build, ubuntu machine) I get the following error:

```
> habitus -f habitus.yaml --host tcp://docker:2345
2016/05/07 14:46:20 ▶ Using 'habitus.yaml' as build file                                 
2016/05/07 14:46:20 ▶ open cert.pem: no such file or directory
```

My Docker doesn't require TLS to connect to. It looks like builder.go (https://github.com/cloud66/habitus/blob/f133be298d74c444bb260684e7b4f6989f4fdb18/build/builder.go#L59-L63) assumes it does.

**Comment by khash** [comment]
@BenHall the latest in dev branch has a switch to turn TLS off now. Will merge into master for the next release.

**Comment by kamerblauwlicht** [comment]
this error is due using the new 'native' Docker mac support which is not using TLS.

**Comment by BenHall** [comment]
How do you specify the use-tls flag? I'm using the 0.3 build but it doesn't seem to accept it

**Comment by khash** [comment]
Non-TLS connection is supported on versions 0.4.5 and above.

**Comment by kienpham2000** [comment]
I have to put this for it to work: `./habitus --use-tls=false`
