### ISSUE TITLE
How to use Habitus with Docker for Mac?

### ISSUE THREAD

**Issue by corvus-ch** [cloud66/habitus#17]
I just have switched to Docker for Mac and I try to figure out how to use Habitus. So far without any luck.

```
➜  habitus                                     
2016/05/22 20:34:43 ▶ Using '/path/to/build.yml' as build file                                                                                               
2016/05/22 20:34:43 ▶ open cert.pem: no such file or directory 
```
```
➜  habitus --use-tls=false
2016/05/22 20:34:50 ▶ Using '/path/to/build.yml' as build file                                                                                               
2016/05/22 20:34:50 ▶ invalid endpoint 
```

**Comment by khash** [comment]
The latest version of Habitus supports Docker for Mac. You need to use a Linux socket to connect with no TLS.

To disable TLS, use the `-use-tls` flag.
To use Linux sockets instead of TCP, you can pass in Docker's socket file into `--host` with something like this:

```
-- host unix://path/to/socket
```

**Comment by bibstha** [comment]
`habitus --use-tls=false --host=unix:///var/run/docker.sock --binding=127.0.0.1` works on both mac and linux with the newer docker versions.

**Comment by mirestrepo** [comment]
@khash - Where do the secret files live when using Linux sockets? 
RUN wget -O /root/.ssh/github_rsa http://$host:8080/secrets/file/id_rsa

gives invalid hostname . I tried replacing $host by 127.0.0.1 and I get connection refused.

**Comment by khash** [comment]
@mirestrepo secret file location doesn't change depending on the how Habitus connects to the Docker daemon. Have you used them on a non-socket connection successfully?

**Comment by mirestrepo** [comment]
@khash Thank you - I figured my issue. Though other issues I realized I should be setting my host to my private ip - ipconfig getifaddr en0

**Comment by kienpham2000** [comment]
the command provided by @bibstha should be listed in the Readme file or something, took me a while to get a basic security build up.
