### ISSUE TITLE
How to install Habitus on mac

### ISSUE THREAD

**Issue by Janendran** [cloud66/habitus#18]
could you please give the steps to install and run habitus on mac os?

**Comment by khash** [comment]
If you want to run it on OSX, you can just download the executable from the Releases of this repo and run it in terminal. To compile clone the repo (go >= 1.6) do a `go get` and `go build` and you will have the executable.

**Comment by Janendran** [comment]
I have tried but didn't work could you give me the commands or please document it correctly.

**Comment by khash** [comment]
@Janendran sorry to hear that. Could you please provide some details about the error and your setup?

**Comment by Janendran** [comment]
so when i do sudo ./habitus_darwin_amd64 i get sudo: ./habitus_darwin_amd64: command not found

**Comment by khash** [comment]
Thank you. Can you send a dump of `ls -la` on the directory you run it from please?

**Comment by Janendran** [comment]
LONC02P40XNG3QN:~ jthiyaganathan$ ls -la
total 147712
drwxr-xr-x+ 120 jthiyaganathan  SEA\Domain Users      4080 Jun 13 12:14 .
drwxr-xr-x    6 root            admin                  204 Jan 27 11:31 ..
-r--------    1 jthiyaganathan  SEA\Domain Users         7 Jan 27 14:11 .CFUserTextEncoding
-rw-r--r--@   1 jthiyaganathan  SEA\Domain Users     26628 Jun  9 12:08 .DS_Store
drwx------  180 jthiyaganathan  SEA\Domain Users      6120 Jun 10 15:18 .Trash
-r--------    1 jthiyaganathan  admin                63878 Jun 13 12:14 .account
drwxr-xr-x   16 jthiyaganathan  SEA\Domain Users       544 Apr 13 14:33 .android
drwxr-xr-x   13 jthiyaganathan  SEA\Domain Users       442 Apr 25 17:49 .atom
drwxr-xr-x    3 jthiyaganathan  SEA\Domain Users       102 Mar  1 17:18 .aws
-rw-r--r--    1 jthiyaganathan  SEA\Domain Users     11439 Jun 10 16:03 .bash_history
-rw-r--r--    1 jthiyaganathan  SEA\Domain Users       411 May 30 11:35 .bash_profile
-rw-------    1 jthiyaganathan  SEA\Domain Users     12288 Feb 11 16:47 .bash_profile.swm
-rw-------    1 jthiyaganathan  SEA\Domain Users     12288 Feb 11 16:35 .bash_profile.swn
-rw-------    1 jthiyaganathan  SEA\Domain Users     12288 Feb 11 16:36 .bash_profile.swo
-rw-------    1 jthiyaganathan  SEA\Domain Users     12288 Feb 11 15:57 .bash_profile.swp
drwxr-xr-x  145 jthiyaganathan  SEA\Domain Users      4930 Jun 10 16:03 .bash_sessions
-rw-r--r--    1 jthiyaganathan  SEA\Domain Users       117 Feb 25 15:53 .bashrc
-rw-------    1 jthiyaganathan  SEA\Domain Users     12288 Feb 18 15:04 .bashrc.swp
drwxr-xr-x    5 jthiyaganathan  SEA\Domain Users       170 Apr  7 21:33 .berkshelf
drwxr-xr-x    3 jthiyaganathan  SEA\Domain Users       102 Apr 29 16:30 .bundle
drwxr-xr-x    7 jthiyaganathan  SEA\Domain Users       238 May 17 17:26 .chef
drwxr-xr-x    4 jthiyaganathan  SEA\Domain Users       136 May 25 15:48 .config
drwxr-xr-x    3 jthiyaganathan  SEA\Domain Users       102 Feb 19 10:45 .cordova
drwx------    3 jthiyaganathan  SEA\Domain Users       102 Mar 15 16:25 .cups
-rw-r--r--    1 jthiyaganathan  SEA\Domain Users        12 Feb 19 12:09 .dbshell
drwxr-xr-x    4 jthiyaganathan  staff                  136 Feb 19 10:44 .docker
drwxr-xr-x    8 jthiyaganathan  SEA\Domain Users       272 Mar  7 18:25 .eclipse
drwxr-xr-x    4 jthiyaganathan  SEA\Domain Users       136 Feb 25 20:33 .gem
drwxr-xr-x   11 jthiyaganathan  SEA\Domain Users       374 Jun  6 13:32 .git
-rw-r--r--    1 jthiyaganathan  SEA\Domain Users       206 May 28 20:02 .gitconfig
drwxr-xr-x    7 jthiyaganathan  SEA\Domain Users       238 Apr 10 09:26 .gradle
drwxr-xr-x   10 jthiyaganathan  SEA\Domain Users       340 Apr 13 14:22 .idea
-rw-r--r--    1 jthiyaganathan  SEA\Domain Users        19 Apr 28 14:48 .irb-history
drwxr-xr-x    4 jthiyaganathan  SEA\Domain Users       136 Jun  6 15:31 .m2
drwxr-xr-x    5 jthiyaganathan  SEA\Domain Users       170 Oct 27  2015 .meteor
-rw-------    1 jthiyaganathan  SEA\Domain Users        90 Feb 18 14:24 .meteorsession
-rw-r--r--    1 jthiyaganathan  SEA\Domain Users        68 Feb 25 15:53 .mkshrc
-rw-------    1 jthiyaganathan  SEA\Domain Users         0 Feb 19 11:40 .mongorc.js
drwxr-xr-x    3 jthiyaganathan  SEA\Domain Users       102 Mar 17 11:11 .mono
drwxr-xr-x    3 jthiyaganathan  SEA\Domain Users       102 May  4 14:48 .node-gyp
drwxr-xr-x    5 jthiyaganathan  SEA\Domain Users       170 Jun 10 15:31 .npm
drwxr-xr-x    4 jthiyaganathan  SEA\Domain Users       136 Mar 27 12:22 .oracle_jre_usage
drwxr-xr-x    8 jthiyaganathan  SEA\Domain Users       272 Mar  7 12:30 .p2
-r--------    1 jthiyaganathan  SEA\Domain Users        88 Jun 13 09:42 .p4tickets
-rw-r--r--    1 jthiyaganathan  SEA\Domain Users       186 Feb 25 15:53 .profile
drwxr-xr-x    3 jthiyaganathan  SEA\Domain Users       102 Apr  8 13:02 .python-eggs
drwxr-xr-x    4 jthiyaganathan  SEA\Domain Users       136 Apr 26 12:56 .reimage
drwxr-xr-x   30 jthiyaganathan  SEA\Domain Users      1020 Feb 25 15:53 .rvm
-rw-------    1 jthiyaganathan  SEA\Domain Users       117 Jun 10 15:28 .sh_history
drwx------    7 jthiyaganathan  SEA\Domain Users       238 Apr 26 15:26 .ssh
drwxr-xr-x    6 jthiyaganathan  SEA\Domain Users       204 Apr  6 14:54 .subversion
drwxr-xr-x    3 jthiyaganathan  SEA\Domain Users       102 Mar  7 18:10 .tooling
drwxr-xr-x    3 jthiyaganathan  SEA\Domain Users       102 Feb 25 15:40 .vagrant
drwxr-xr-x   10 jthiyaganathan  SEA\Domain Users       340 May 28 19:43 .vagrant.d
-rw-------    1 jthiyaganathan  SEA\Domain Users      7855 Jun  6 13:41 .viminfo
-rw-r--r--    1 jthiyaganathan  SEA\Domain Users       334 May 30 09:42 .wget-hsts
-rw-r--r--    1 jthiyaganathan  SEA\Domain Users       118 Feb 25 15:53 .zlogin
-rw-r--r--    1 jthiyaganathan  SEA\Domain Users        68 Feb 25 15:53 .zshrc
drwxr-xr-x@  21 jthiyaganathan  SEA\Domain Users       714 Feb 21 14:07 AdminLTE-2.3-2.0
drwxr-xr-x   22 jthiyaganathan  SEA\Domain Users       748 Mar  7 12:05 AkamaiECCU
drwx------    9 jthiyaganathan  SEA\Domain Users       306 Jun  9 17:22 Applications
drwxr-xr-x@   4 jthiyaganathan  SEA\Domain Users       136 May 23 11:24 Applications (Parallels)
drwx------+  75 jthiyaganathan  SEA\Domain Users      2550 Jun 10 12:57 Desktop
drwx------+  14 jthiyaganathan  SEA\Domain Users       476 Jun 10 13:27 Documents
drwx------+ 147 jthiyaganathan  SEA\Domain Users      4998 Jun 10 13:29 Downloads
drwxr-xr-x  133 jthiyaganathan  SEA\Domain Users      4522 Mar  9 13:52 EosRegistryDr
drwx------@  61 jthiyaganathan  SEA\Domain Users      2074 May 23 10:08 Library
drwx------+   5 jthiyaganathan  SEA\Domain Users       170 Mar  2 17:42 Movies
drwx------+   5 jthiyaganathan  SEA\Domain Users       170 Apr  5 11:07 Music
drwxr-xr-x    5 jthiyaganathan  SEA\Domain Users       170 Apr 21 13:42 Perforce
drwx------+   5 jthiyaganathan  SEA\Domain Users       170 Mar  2 17:42 Pictures
drwxr-xr-x+   5 jthiyaganathan  SEA\Domain Users       170 Feb 19 10:44 Public
drwxr-xr-x   19 jthiyaganathan  SEA\Domain Users       646 Apr 25 14:37 SeleniumGridScalerExp
drwxr-xr-x    4 jthiyaganathan  SEA\Domain Users       136 May 12 18:15 Trello-Git
-rw-r--r--    1 jthiyaganathan  SEA\Domain Users      3016 Feb 25 17:15 Vagrantfile
drwx------    8 jthiyaganathan  SEA\Domain Users       272 May 28 19:39 VirtualBox VMs
drwxr-xr-x   11 jthiyaganathan  SEA\Domain Users       374 Jun  6 13:41 angelbanzaidemo04-web
drwxr-xr-x@   9 jthiyaganathan  SEA\Domain Users       306 Apr 11 11:50 build
drwxr-xr-x@  15 jthiyaganathan  SEA\Domain Users       510 Apr 28 15:53 chef-repo
drwx------    3 jthiyaganathan  SEA\Domain Users       102 Dec  4  2013 chef-server
-rw-r--r--    1 jthiyaganathan  SEA\Domain Users  59075195 Feb 26 10:24 chef-server-11.0.8-1.el6.x86_64.rpm
-rw-------    1 jthiyaganathan  SEA\Domain Users      6343 Feb 29 11:56 chef-teamcity-1.0.0.tar.gz
drwxr-xr-x   12 jthiyaganathan  SEA\Domain Users       408 May  9 09:46 coreroller
drwxr-xr-x   13 jthiyaganathan  SEA\Domain Users       442 Jun  6 15:51 cruise-web
drwxr-xr-x    2 jthiyaganathan  SEA\Domain Users        68 Feb 18 15:58 d
drwxr-xr-x   22 jthiyaganathan  SEA\Domain Users       748 Feb 19 15:52 dashboard
drwxr-xr-x   10 jthiyaganathan  SEA\Domain Users       340 Mar 27 10:00 docker-birthday-3
drwxr-xr-x    3 jthiyaganathan  SEA\Domain Users       102 Mar  7 12:28 eclipse
drwxr-xr-x   18 jthiyaganathan  SEA\Domain Users       612 May 26 15:26 ewe-ios-cli
-rw-r--r--    1 jthiyaganathan  SEA\Domain Users     18432 Dec 21 14:56 ewe-reimage-tools-1.1.0.gem
drwxr-xr-x   31 jthiyaganathan  SEA\Domain Users      1054 Jun  9 15:18 ewe-trello-burndown-sinatra
drwxr-xr-x   32 jthiyaganathan  SEA\Domain Users      1088 Apr 29 16:30 ewe-trello-dashboard-sinatra
drwxr-xr-x   11 jthiyaganathan  SEA\Domain Users       374 May 28 17:43 exp-devops
drwxr-xr-x    7 jthiyaganathan  SEA\Domain Users       238 May 15 19:44 expandable-table-view
drwxr-xr-x   27 jthiyaganathan  SEA\Domain Users       918 May 30 10:19 habitus
-rw-r--r--@   1 jthiyaganathan  SEA\Domain Users  12236688 May 10 18:15 habitus_darwin_amd64
drwxr-xr-x    7 jthiyaganathan  SEA\Domain Users       238 Feb 19 10:45 mongodb
drwxr-xr-x    7 jthiyaganathan  SEA\Domain Users       238 Feb 19 10:15 mongodb-osx-x86_64-3.2.3
drwxr-xr-x    8 jthiyaganathan  SEA\Domain Users       272 May 16 17:12 monitoring
drwxr-xr-x   20 jthiyaganathan  SEA\Domain Users       680 Feb 19 15:51 myapp
drwxr-xr-x    5 jthiyaganathan  SEA\Domain Users       170 Feb 19 12:35 mydockerbuild
drwxr-xr-x  104 jthiyaganathan  SEA\Domain Users      3536 Apr 11 12:04 node_modules
drwxr-xr-x    6 jthiyaganathan  SEA\Domain Users       204 Jun  7 15:50 nomad
drwxr-xr-x   32 jthiyaganathan  SEA\Domain Users      1088 Apr 27 21:58 ollert
drwxr-xr-x    8 jthiyaganathan  SEA\Domain Users       272 Apr 18 12:51 platform-samples
drwxr-xr-x    6 jthiyaganathan  SEA\Domain Users       204 Feb 19 11:56 polling
drwxr-xr-x@  11 jthiyaganathan  SEA\Domain Users       374 Nov 17  2015 sb-admin
-rw-r--r--@   1 jthiyaganathan  SEA\Domain Users        11 May 19 10:02 set.text
drwxr-xr-x    5 jthiyaganathan  SEA\Domain Users       170 Feb 23 16:19 site
drwxr-xr-x    9 jthiyaganathan  SEA\Domain Users       306 Feb 19 11:56 todos
drwxr-xr-x   16 jthiyaganathan  SEA\Domain Users       544 Jun  7 17:21 tomcruise-web
drwxr-xr-x   19 jthiyaganathan  SEA\Domain Users       646 Apr 11 12:13 trello-burndown
drwxr-xr-x   16 jthiyaganathan  SEA\Domain Users       544 Apr 14 17:30 trello-github-issue-manager
drwxr-xr-x   16 jthiyaganathan  SEA\Domain Users       544 Apr  8 14:02 trelloburndown
drwxr-xr-x    7 jthiyaganathan  SEA\Domain Users       238 Jun  6 11:26 userservice
drwxr-xr-x    9 jthiyaganathan  SEA\Domain Users       306 Apr 19 14:17 vagrant-chef-wordpress
drwxr-xr-x   17 jthiyaganathan  SEA\Domain Users       578 Apr 19 15:08 vagrant-wp
drwxr-xr-x    2 jthiyaganathan  SEA\Domain Users        68 Feb 25 17:47 vagrant_vm
drwxr-xr-x    3 jthiyaganathan  SEA\Domain Users       102 Feb 25 16:29 wget-1.16.3
-rw-r--r--    1 jthiyaganathan  SEA\Domain Users   4039990 Apr 19 14:08 wp-cli.phar

**Comment by Janendran** [comment]
-rw-r--r--@   1 jthiyaganathan  SEA\Domain Users  12236688 May 10 18:15 habitus_darwin_amd64

**Comment by khash** [comment]
Thank you. What do you get when you run `./habitus_darwin_amd64` (without sudo)?

**Comment by Janendran** [comment]
LONC02P40XNG3QN:~ jthiyaganathan$ ./habitus_darwin_amd64
-bash: ./habitus_darwin_amd64: Permission denied

**Comment by khash** [comment]
It seems we are not even getting to run the executable yet. I can't be sure how the tar file was extracted but looking at the file permissions it seems it doesn't have execution rights. You can try `sudo chmod +x habitus_darwin_amd64` to make it executable.

**Comment by Janendran** [comment]
thanks @khash

**Comment by Janendran** [comment]
▶ Using '/Users/jthiyaganathan/habitus_test/build.yml' as build file 
 ▶ open cert.pem: no such file or directory 

any idea how to fix this?

**Comment by iDVB** [comment]
Part of the confusion, for me, at least is that the file in the downloads section for macOS and linux does not seem to have an extension. So its a bit of a guessing game on what to do with it. I've already tried adding *.tar to it (based on your mention above) with no success.
