### ISSUE TITLE
Execute command as part of 'after build' for example docker push

### ISSUE THREAD

**Issue by bibstha** [cloud66/habitus#19]
Is there a way to do 'docker push' for example after building the image.
I have a custom script that does 'docker build' and would like to push the image to a private repository for example. I handle this via a shell script. Habitus being a build tool, would be nice to have a section that lists commands that executes outside of the container after each build step so I can get rid of the shell script.

**Comment by khash** [comment]
The aim is to keep Habitus a build tool and not a complete CI/CD, but I can see how this can be a very useful addition. Covering all scenarios involving credentials and tagging is the main challenge stopping us. If you have a working prototype would be great!
