### ISSUE TITLE
build error on log

### ISSUE THREAD

**Issue by linearregression** [cloud66/habitus#21]
./main.go:72: cannot use *log (type "github.com/op/go-logging".Logger) as type "github.com/cloud66/habitus/vendor/github.com/op/go-logging".Logger in assignment

From:
go get 
then 
go build

**Comment by khash** [comment]
Can you confirm the version of go you're running please by running `go version`?

**Comment by linearregression** [comment]
go version go1.6.2 darwin/amd64

**Comment by linearregression** [comment]
It is an issue because dependencies in the vendor.

https://github.com/mattfarina/golang-broken-vendor

**Comment by kamerblauwlicht** [comment]
update the vendoring in the dev branch.
