### ISSUE TITLE
Artifacts may only be a file?

### ISSUE THREAD

**Issue by mfeckie** [cloud66/habitus#23]
Is there a way to collect a whole directory?

Example, with Elixir releases we get a directory that represents the artifact `/rel`, passing this to artifacts in the `build.yml` results in an 'Invalid Header' error.

**Comment by sebest** [comment]
A workaround is to do a RUN tar cfz in the build step and then ADD the tar.gz in the deployment step as tar.gz is natively supported by Dockerfile
Do not forget to list the tar.gz in the artifacts.

I'm doing this here: https://github.com/sebest-blog/create-a-small-docker-image-for-a-golang-binary-with-habitus

Look for zoneinfo in Dockerfile.* and build.yml
