### ISSUE TITLE
tar: Option --xattrs is not supported on OS X el Capitan

### ISSUE THREAD

**Issue by jmversteeg** [cloud66/habitus#25]
When I try building an image on an OS X El Capitan host, the following error is thrown once the `squash` step is reached:

```
2016/09/01 23:52:01 ▶ Loading export from /tmp/habitus-export-527359243 using /tmp/docker-squash612669813 for tempdir 
2016/09/01 23:52:02 ▶ Loaded image w/ 18 layers 
2016/09/01 23:52:02 ▶ Extracting layers... 
2016/09/01 23:52:02 ▶   -  /tmp/docker-squash612669813/036fc864e6c7d0b6f75fe523e4a1a852f72115062e76f0a9d14877989948eb4a/layer.tar 
tar: Option --xattrs is not supported
Usage:
  List:    tar -tf <archive-filename>
  Extract: tar -xf <archive-filename>
  Create:  tar -cf <archive-filename> [filenames...]
  Help:    tar --help

2016/09/01 23:52:02 ▶ Build for step carrier failed due to exit status 1 
```

I am fairly sure [this](https://github.com/cloud66/habitus/blob/f133be298d74c444bb260684e7b4f6989f4fdb18/squash/utils.go#L17) line is causing the problem however I am not knowledgeable enough in this area to actually resolve the problem.

[Related issue on docker-squash](https://github.com/jwilder/docker-squash/issues/10)

[Dirty work-around](https://github.com/jwilder/docker-squash/issues/10#issuecomment-241060901), I have tested and this does work however it feels like there should be a neater solution to this problem

**Comment by jmversteeg** [comment]
I am fairly sure [this](https://github.com/cloud66/habitus/blob/f133be298d74c444bb260684e7b4f6989f4fdb18/squash/utils.go#L17) line is causing the problem however I am not knowledgeable enough in this area to actually resolve the problem.

**Comment by kamerblauwlicht** [comment]
hi jim. because there is more information stored in the image layers, we need the --xattrs parameter. we can't create a switch in the code saying... if mac_ox_s don't use --xattrs. It feels a bit a like hack indeed. but we must blame Apple not to include a better version of Tar ;-)

**Comment by kamerblauwlicht** [comment]
hi @jmversteeg! check this page https://github.com/cloud66/habitus/blob/gh-pages/gnu-tar.md
