### ISSUE TITLE
CMD / ENTRYPOINT are not repected in the exec format

### ISSUE THREAD

**Issue by sebest** [cloud66/habitus#26]
Hello

It seems that if I use CMD ["/my_binary"] in my Docker.deployment it is considered as if i typed: CMD /my_binary

This is what i expect when running docker inspect:
```
            "Cmd": [
                "/main"
            ],
```
and this is what i get using habitus:
```
            "Cmd": [
                "/bin/sh",
                "-c",
                "/main"
            ],
```

If i use docker build with the exact same dockerfile it works as expected.

I did an example to reproduce the issue:
https://github.com/sebest-blog/create-a-small-docker-image-for-a-golang-binary-with-habitus

**Comment by kamerblauwlicht** [comment]
#30 is related
