### ISSUE TITLE
Suggestion, prefix output logs with step name

### ISSUE THREAD

**Issue by alledm** [cloud66/habitus#38]
The log when running multiple images in parallel seems confusing and difficult to follow.
When it gets to the actual docker steps, it becomes impossible to understand which command relates to which step.

```
2016/10/19 12:58:53 Parallel build for go_base
2016/10/19 12:58:53 Parallel build for frontend_api
2016/10/19 12:58:53 Building go_base
2016/10/19 12:58:53 Building frontend_api
2016/10/19 12:58:53 Parsing and converting 'Dockerfile.go_base'
2016/10/19 12:58:53 Parsing and converting 'Dockerfile.frontend_api'
2016/10/19 12:58:53 Writing the new Dockerfile into Dockerfile.go_base.generated
2016/10/19 12:58:53 Parallel build for hdl7 [0m
2016/10/19 12:58:53 Building hdl7 [0m
2016/10/19 12:58:53 Parsing and converting 'Dockerfile.hdl7
```

would it be possible to tag these lines with something like the step name or number so it is easies to understand which step they refer to?

regards
Alessandro

**Comment by kamerblauwlicht** [comment]
make total sense. added to milestone

**Comment by kamerblauwlicht** [comment]
make total sense.
