### ISSUE TITLE
open cert.pem: no such file or directory

### ISSUE THREAD

**Issue by benzid-wael** [cloud66/habitus#39]
When I run _habitus_, I get the following error

> $ sudo habitus_linux_amd64
> 2016/10/24 12:16:43 ▶ Using '/home/wael/myProject/build.yml' as build file  
> 2016/10/24 12:16:43 ▶ open cert.pem: no such file or directory

**Environment**:
- OS: Ubuntu 16.04
- Docker: 1.12.1, build 23cf638

Docker is installed locally and does not require TLS for connection

**Comment by denneulin** [comment]
https://github.com/cloud66/habitus/issues/17
