### ISSUE TITLE
Need example yml file

### ISSUE THREAD

**Issue by josephschorr** [cloud66/habitus#4]
Currently hard to know how to quickly get everything configured

**Comment by jzelinskie** [comment]
You added a config.json which contains yaml.

**Comment by Kasia66** [comment]
Hi Jimmy,

Thank you very much for pointing that out. It is fixed now. :)

If you have any questions, please let me know I am always happy to help.

Kind regards,
Kasia

On 23 February 2016 at 23:38, Jimmy Zelinskie <notifications@github.com>
wrote:

> You added a config.json which contains yaml.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloud66/habitus/issues/4#issuecomment-187968596>.
>



-- 
Kasia Hoffman
Developer Outreach
Cloud 66 - DevOps as a Service. <http://www.cloud66.com/>
Watch Cloud 66 video <https://vimeo.com/140805437>.
