### ISSUE TITLE
cannot get into the cloud66 slack team.

### ISSUE THREAD

**Issue by hsyed** [cloud66/habitus#41]
Hello folks. You list your slack team on the git readme but it doesn't let people signup unless they have been approved. 

The following URL is meant to allow signup:

https://cloud66ers.slack.com/signup

**Comment by khash** [comment]
Thanks for reporting this @hsyed we will try to fix this. In the meantime, you can join the Slack channel from by signing up at Cloud66.com and using the link from your account after logging in.

**Comment by Kasia66** [comment]
This is the link that we use to signup to Cloud 66 Community Slack: https://app.cloud66.com/accounts/join_slack_channel

It should work without signup-approval. @kamerblauwlicht
