### ISSUE TITLE
Install Instructions

### ISSUE THREAD

**Issue by ccarterc** [cloud66/habitus#42]
I might be missing it, but have been looking at docs for a while and still unable to find any instructions on how to install for linux.  Maybe docs could take the following format: 

Step 1: Install
Type this command to install `blah blah blah`

Step 2: Use
...

**Comment by kamerblauwlicht** [comment]
hi @ccarterc. thanks. will update the docs when we have the time.

**Comment by iDVB** [comment]
Also interested in how to install. 
none of the binaries have a file type, so we're kind of guessing what to do with it.

**Comment by iDVB** [comment]
suggestion in https://github.com/cloud66/habitus/issues/18 solved it.
