### ISSUE TITLE
ENTRYPOINT instruction is modified from exec format to shell format

### ISSUE THREAD

**Issue by mangalaman93** [cloud66/habitus#43]
```
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["ls"]
```

gets modified to 
```
entrypoint /docker-entrypoint.sh
CMD ["ls"]
```

Is that an expected behaviour?

**Comment by kamerblauwlicht** [comment]
no. it shouldn't. i fixed the issue with CMD a couple of weeks back. need to do the same with entrypoint. thanks for bringing this up.

**Comment by kamerblauwlicht** [comment]
will add this to the next milestone.

**Comment by mangalaman93** [comment]
I can create a pull request, I already have thus change in my fork.
