### ISSUE TITLE
"cleanup" commands cannot run if USER was set to != root in Dockerfile

### ISSUE THREAD

**Issue by chdeliens** [cloud66/habitus#44]
In our Dockerfile, we have some steps that we do execute using another user than root, resulting in the cleanup command `rm -rf /root/.ssh/` not to execute:
> `rm: cannot remove '/root/.ssh/': Permission denied`

Easy fix was to have command `USER root` as the last entry of our Dockerfile, but that's a temporary hack 😄

**Comment by kamerblauwlicht** [comment]
hi @chdeliens. thanks for the ticket.

**Comment by kamerblauwlicht** [comment]
@chdeliens I checked the code and we run the cleanup command using a `docker exec` command against your build image, this means the cleanup command is run as the last user set with the `USER xxx` in the Dockerfile. It's up to the maintainer of the Dockerfile how to deal with it. I leave this ticket for reference and help.

If you have an elegant solution to tackle this use case, please let me know.

**Comment by neverfox** [comment]
> It's up to the maintainer of the Dockerfile how to deal with it.

I'm not sure I understand what you mean. Some Dockerfile are like this for a reason. Wouldn't the elegant solution be to allow for providing a user for the cleanup command in the build.yml and then using that in the --user flag to docker exec?
