### ISSUE TITLE
Keep flag?

### ISSUE THREAD

**Issue by mgomezch** [cloud66/habitus#47]
[The description for the  `--keep-all` option](https://github.com/cloud66/habitus/blob/be2d748ed664912053249e58e9cf19f1412605ee/main.go#L60) seems to suggest the existence of a `keep` flag for individual steps that would prevent image removal for intermediate steps:

```
	flag.BoolVar(&config.KeepSteps, "keep-all", false, "Overrides the keep flag for all steps. Used for debugging")
```

Does such a flag actually exist?

**Comment by kamerblauwlicht** [comment]
yes. it does. if you check the builder.go you can find the keep switch not to remove the intermediate steps

**Comment by mgomezch** [comment]
Sorry for hammering on, but I can't quite find the keep flag that is said to be overridden for all steps in that help text.  I did find this in `builder.go`:

```

	if b.Conf.KeepSteps {
		return nil
	}

	if len(b.Build.Steps) < 1 {
		b.Conf.Logger.Fatal("No build steps found")
	}

	// Clear after yourself: images, containers, etc (optional for premium users)
	// except last step
	for _, s := range b.Build.Steps[:len(b.Build.Steps)-1] {
		b.Conf.Logger.Debugf("Removing unwanted image %s", b.uniqueStepName(&s))
		rmiOptions := docker.RemoveImageOptions{Force: b.Conf.FroceRmImages, NoPrune: b.Conf.NoPruneRmImages}
		err := b.docker.RemoveImageExtended(b.uniqueStepName(&s), rmiOptions)
		if err != nil {
			return err
		}
	}
```

Indeed the first part of that has the implementation of the global `keep-all` command-line option that keeps intermediate images for *all* steps, but the help text for that option appears to suggest an option exists to control this behavior (the mentioned "keep flag") for individual steps.  From the loop in the second part of that code from `builder.go`, it does not appear to exist.

Is this a missing feature implementation or a documentation bug in the help message, or am I just reading it wrong?
