### ISSUE TITLE
travisci command error

### ISSUE THREAD

**Issue by toonsevrin** [cloud66/habitus#52]
So I wanted to test habitus and made [this project](https://github.com/toonsevrin/testhabitus). When travisci builds it, this is the output:

```
$ sudo wget https://github.com/cloud66/habitus/releases/download/0.4.9/habitus_linux_amd64 -o habitus

$ sudo chmod +x habitus

$ sudo ./habitus -version
./habitus: 1: ./habitus: --2017-02-19: not found
./habitus: 2: ./habitus: Syntax error: "(" unexpected


The command "sudo ./habitus -version" failed and exited with 2 during .

Your build has been stopped.
```

**Comment by kamerblauwlicht** [comment]
Hi @toonsevrin 

Thanks for reaching out.  I tested your commands, and your **wget** command has the wrong output switch. You need to use **-O** instead of **-o**. 

`wget https://github.com/cloud66/habitus/releases/download/0.4.9/habitus_linux_amd64 -O habitus`

**Comment by toonsevrin** [comment]
-_- sorry bout that

**Comment by toonsevrin** [comment]
0.01s$ sudo ./habitus --no-cache
2017/02/20 22:25:45 ▶ Using '/home/travis/build/toonsevrin/testhabitus/build.yml' as build file 
2017/02/20 22:25:45 ▶ Collecting artifact information 
2017/02/20 22:25:45 ▶ Starting API on 8080 
2017/02/20 22:25:45 ▶ Failed to start API listen tcp 192.168.99.1:8080: bind: cannot assign requested address 
The output I receive now :(

**Comment by toonsevrin** [comment]
#50 solved it 👍

**Comment by kamerblauwlicht** [comment]
@toonsevrin good to hear! have fun using habitus on travis!

**Comment by toonsevrin** [comment]
Thanks! going to use it for the secret management
