### ISSUE TITLE
Add secret type for environment variables

### ISSUE THREAD

**Issue by toonsevrin** [cloud66/habitus#53]
Our building environment is completely isolated and defining our secrets as env variables on the host is the easiest way for us to manage build time secrets. It would be great to see environment variables implemented as a secret type.

**Comment by kamerblauwlicht** [comment]
hi @toonsevrin thanks for the feedback. looking into how  we can implement this.

**Comment by toonsevrin** [comment]
Just make sure you can define which environment variables are propagated, then these can be fetched with the webserver.

What would be really cool is if these variables are available as envvars within the build, but I assume that's impossible.

**Comment by kamerblauwlicht** [comment]
hi @toonsevrin  I implemented this feature. Will add some docs and will release today

**Comment by toonsevrin** [comment]
That's great, we are now using two phase building and are quite happy with this, but I'm sure this will be of use to other developers!
