### ISSUE TITLE
cannot use habitus CLI environment variables with secrets

### ISSUE THREAD

**Issue by johnphho** [cloud66/habitus#55]
As soon as I use --env variables I can no longer access secret files.  When I remove the environment variables it works.

**Comment by kamerblauwlicht** [comment]
hi @johnphho 

thanks for the bug report. any change you found the bug in the code?

**Comment by johnphho** [comment]
Sorry, I haven't had time to do so but I believe everything works if I don't use secrets.  I really need this fixed because I need to use ENV variables.  Thanks

**Comment by kamerblauwlicht** [comment]
@johnphho  can you show me how you run the `habitus` command and how your `build.yml` looks like?

**Comment by armangharib** [comment]
habitus command and how your build.yml

**Comment by kamerblauwlicht** [comment]
you need to enable the secret service with the `--secrets=true` switch. will update docs
