### ISSUE TITLE
parse Dockerfiles for _env(x) to get substituted with parent environment variables or with the --env switch 

### ISSUE THREAD

**Issue by kamerblauwlicht** [cloud66/habitus#59]

**Comment by timriley** [comment]
I'm interested in understanding why you didn't implement this in the end – would you mind sharing some insight into this? Was it because you implemented support for secrets coming from env vars, or some other reason?

**Comment by kamerblauwlicht** [comment]
Hi @timriley! Thanks for the feedback. Because of security reasons we decided to go for the secret service. If we substitute host environment variables this can be potentially dangerous. This was a feature we wanted to use in our Buildgrid buildsystems over at Cloud 66, but the secrets coming from the secret service giving us more control. If you have a good use-case, please share. We can always reopen the issue if more people want this ;-)
