### ISSUE TITLE
Add ability to define a volume on intermediate containers

### ISSUE THREAD

**Issue by roytruelove** [cloud66/habitus#60]
This would be hugely helpful in the case of java maven builds.

I'm familiar with the trick of copying over just the `pom.xml` (not forgetting your submodules) and running `mvn dependency:resolve` (demonstrated nicely [here](http://blog.cloud66.com/create-construct-and-weld-the-perfect-production-ready-secure-java-container-with-habitus-io/)).  Changes to `pom.xml` files are common enough occurrences, however, and in my case a change to a pom incurs a ~200mb download.  Since my CI is hosted in the cloud that's a lot of network usage, which can get $$$.

If the dependencies were instead exposed in a volume, they would be downloaded only once for the lifetime of the project.

**Comment by kamerblauwlicht** [comment]
Hi @roytruelovem,

The big problem here is that you can't use **volumes** in the **build** process, only copy files into images from the host. Habitus now has support for coping directories out of a build step. For example copy the `pom` results out of a step and inject them in the next one, and leave them on the host system. Make sense?

**Comment by roytruelove** [comment]
@kamerblauwlicht thanks for your timely and helpful response

> The big problem here is that you can't use volumes in the build process
Ah yes, that throws a bit of a wrench in the idea :)
>  Habitus now has support for coping directories out of a build step ... and leave them on the host system
I haven't been able to determine how to do this except for using the `keep-artifacts` flag, which the help says is only for debugging purposes.  I _can_ use it, but using it leads me to believe that I'm using Habitus in a way in which it was not intended...?

**Comment by kamerblauwlicht** [comment]
between build steps the artifacts stay on the host system. hope you worked it out?
