### ISSUE TITLE
Better Document the --secrets option

### ISSUE THREAD

**Issue by naemono** [cloud66/habitus#66]
From struggling myself to get this tool working, and reading through many, many GH issues about similar issues, it turns out that my problem was that I wasn't using '--secrets=true', so it literally wasn't binding to the proper ip address, even though secrets were in the build.yml.

Maybe
1. Automagically turn on secrets when secrets are in build.yml?
2. Update docs to document that feature a bit clearer  (Btw, can you point me to where I can submit a PR for docs, specific to habitus?)

Thanks for a great tool!

**Comment by kamerblauwlicht** [comment]
Hi @naemono,

Yes we changed the behaviour of secrets. Will update the documents. 

Thanks!

Daniel.
