### ISSUE TITLE
Secrets do not work for versions after 0.4.9

### ISSUE THREAD

**Issue by lukogex** [cloud66/habitus#68]
```shell
sudo habitus_linux_amd64 --binding=172.17.42.1 --port=7777 --host unix:///var/run/docker.sock --build host=172.17.42.1
```
Version 0.4.9
```shell
--2017-05-19 09:29:41--  http://172.17.42.1:7777/v1/secrets/file/id_rsa
Connecting to 172.17.42.1:7777... connected.
HTTP request sent, awaiting response... 200 OK
```
Versions after:
```shell
--2017-05-19 09:31:11--  http://172.17.42.1:7777/v1/secrets/file/id_rsa
Connecting to 172.17.42.1:7777... failed: Connection refused.
```
It seems to me that the API do not start. Added a sleep to the docker build to check the port and there was none. Also the log misses the "2017/05/19 11:29:41 ▶ Starting API on 7777" line.

**Comment by kamerblauwlicht** [comment]
thanks @lukogex for the report

**Comment by kamerblauwlicht** [comment]
hi @lukogex after version 0.4.9 you need to enable the secret service with option **--secrets=true**. 
will update the documentation
your command looks like this:
`sudo habitus_linux_amd64 --binding=172.17.42.1 --port=7777 --host unix:///var/run/docker.sock --build host=172.17.42.1 --secrets=true`

**Comment by lukogex** [comment]
Thanks for the information, worked now also for the latest version.
