### ISSUE TITLE
Homebrew Cask?

### ISSUE THREAD

**Issue by nikolay** [cloud66/habitus#72]

**Comment by kamerblauwlicht** [comment]
I added a simple install script. 
https://github.com/cloud66/habitus/blob/master/habitus_install.sh

Just run `curl -sSL https://raw.githubusercontent.com/cloud66/habitus/master/habitus_install.sh | bash`

@nikolay  if you have any direction how to maintain a `homebrew cask` really easy and automated, please let us know or do a PR and I'm happy to add it.

**Comment by kamerblauwlicht** [comment]
we not going to support homebrew cask. the new install script is doing the trick and easier to maintain.
