### ISSUE TITLE
Not working with SSL client certificates

### ISSUE THREAD

**Issue by Alexilmarranen** [cloud66/habitus#76]
During build if mage is in the registry with SSL certs client verification, an error occurs in pulling the image. At the same time, the official Docker has the function of working with [client certs](https://docs.docker.com/engine/security/certificates/). 
I think it's **very** important function for *security*.

Maybe I did not find any mention this function in the documentation?

**Comment by kamerblauwlicht** [comment]
Hi @Alexilmarranen 

You can use the --cert switch to tell which `client certs` to use.

Daniël.
