### ISSUE TITLE
Windows Installer not working

### ISSUE THREAD

**Issue by mleffert** [cloud66/habitus#77]
Downloaded latest install file and it opens then immediatly closes. Nothing gets installed.  Any help would be greatly appreciated.

**Comment by kamerblauwlicht** [comment]
Hi @mleffert 

Can you try to download the binary directly from:
https://github.com/cloud66/habitus/releases/tag/1.0.1
Make sure you can execute it. 
Can you run ` habitus -version` from the command line to see if Habitus works? 
Please report if it doesn't work.

**Comment by mleffert** [comment]
Thanks for the response @kamerblauwlicht  unfortunatly still not working habitus is not a 
recoginzied command
