### ISSUE TITLE
Failing to start API, bind can't assign the requested address

### ISSUE THREAD

**Issue by spacether** [cloud66/habitus#78]
Failed to start API listen tcp 192.168.99.1:8080: bind: can't assign requested address

System: Mac OS X, 64 bit
Dockerfile and build.yml file are in the same directory

Command that I tried to run is:
habitus --build host=192.168.99.1 --secrets=true --binding=192.168.99.1
Changing the ip inputs in both arguments still resulted in the same error

Omitting both ip arguments and keeping secrets still resulted in the above error.

**Comment by spacether** [comment]
It works with 127.0.0.1

**Comment by kamerblauwlicht** [comment]
hi @spacether  good to know you figured it out. ` 192.168.99.1` is just an IP address as an example. when you run habitus on macosx you can bind to 127.0.0.1 or the IP address of your network interface.
